export const GET_SINGLEGUEST_REQUEST = "GET_SINGLEGUEST_REQUEST";
export const GET_SINGLEGUEST_SUCCESS = "GET_SINGLEGUEST_SUCCESS";
export const GET_SINGLEGUEST_FAIL = "GET_SINGLEGUEST_FAIL";

export const NOTIFY_HOST_REQUEST = "NOTIFY_HOST_REQUEST";
export const NOTIFY_HOST_SUCCESS = "NOTIFY_HOST_SUCCESS";
export const NOTIFY_HOST_FAIL = "NOTIFY_HOST_FAIL";
export const NOTIFY_HOST_RESET = "NOTIFY_HOST_RESET";

export const CHECKIN_REQUEST = "CHECKIN_REQUEST";
export const CHECKIN_SUCCESS = "CHECKIN_SUCCESS";
export const CHECKIN_FAIL = "CHECKIN_FAIL";
export const CHECKIN_RESET = "CHECKIN_RESET";

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";
export const CHECKOUT_RESET = "CHECKOUT_RESET";

export const PREBOOK_REQUEST = "PREBOOK_REQUEST";
export const PREBOOK_SUCCESS = "PREBOOK_SUCCESS";
export const PREBOOK_FAIL = "PREBOOK_FAIL";
export const PREBOOK_RESET = "PREBOOK_RESET";

export const SPREBOOK_REQUEST = "SPREBOOK_REQUEST";
export const SPREBOOK_SUCCESS = "SPREBOOK_SUCCESS";
export const SPREBOOK_FAIL = "SPREBOOK_FAIL";
export const SPREBOOK_RESET = "SPREBOOK_RESET";
