export const STAFF_APPROVAL_REQUEST = "STAFF_APPROVAL_REQUEST";
export const STAFF_APPROVAL_SUCCESS = "STAFF_APPROVAL_SUCCESS";
export const STAFF_APPROVAL_FAIL = "STAFF_APPROVAL_FAIL";
export const STAFF_APPROVAL_RESET = "STAFF_APPROVAL_RESET";

export const STAFF_REJECT_REQUEST = "STAFF_REJECT_REQUEST";
export const STAFF_REJECT_SUCCESS = "STAFF_REJECT_SUCCESS";
export const STAFF_REJECT_FAIL = "STAFF_REJECT_FAIL";
export const STAFF_REJECT_RESET = "STAFF_REJECT_RESET";

export const STAFF_R_REQUEST = "STAFF_R_REQUEST";
export const STAFF_R_SUCCESS = "STAFF_R_SUCCESS";
export const STAFF_R_FAIL = "STAFF_R_FAIL";
export const STAFF_R_RESET = "STAFF_R_RESET";
