export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";
export const STAFF_LOGOUT = "STAFF_LOGOUT";

export const MYVISITORS_REQUEST = "MYVISITORS_REQUEST";
export const MYVISITORS_SUCCESS = "MYVISITORS_SUCCESS";
export const MYVISITORS_FAIL = "MYVISITORS_FAIL";

export const STAFF_PREBOOK_REQUEST = "STAFF_PREBOOK_REQUEST";
export const STAFF_PREBOOK_SUCCESS = "STAFF_PREBOOK_SUCCESS";
export const STAFF_PREBOOK_FAIL = "STAFF_PREBOOK_FAIL";
export const STAFF_PREBOOK_RESET = "STAFF_PREBOOK_RESET";

export const GSTAFF_PREBOOK_REQUEST = "GSTAFF_PREBOOK_REQUEST";
export const GSTAFF_PREBOOK_SUCCESS = "GSTAFF_PREBOOK_SUCCESS";
export const GSTAFF_PREBOOK_FAIL = "GSTAFF_PREBOOK_FAIL";

export const STAFF_LOGS_REQUEST = "STAFF_LOGS_REQUEST";
export const STAFF_LOGS_SUCCESS = "STAFF_LOGS_SUCCESS";
export const STAFF_LOGS_FAIL = "STAFF_LOGS_FAIL";

export const STAFF_PENDING_REQUEST = "STAFF_PENDING_REQUEST";
export const STAFF_PENDING_SUCCESS = "STAFF_PENDING_SUCCESS";
export const STAFF_PENDING_FAIL = "STAFF_PENDING_FAIL";
