export const USER_TOKEN_REQUEST = "USER_PREBOOK_REQUEST";
export const USER_TOKEN_SUCCESS = "USER_PREBOOK_SUCCESS";
export const USER_TOKEN_FAIL = "USER_PREBOOK_FAIL";
export const USER_TOKEN_RESET = "USER_PREBOOK_RESET";
