export const FIRST_TIME_GUEST_REQUEST = "FIRST_TIME_GUEST_REQUEST";
export const FIRST_TIME_GUEST_SUCCESS = "FIRST_TIME_GUEST_SUCCESS";
export const FIRST_TIME_GUEST_FAIL = "FIRST_TIME_GUEST_FAIL";
export const FIRST_TIME_GUEST_RESET = "FIRST_TIME_GUEST_RESET";

export const RETURNING_GUEST_REQUEST = "RETURNING_GUEST_REQUEST";
export const RETURNING_GUEST_SUCCESS = "RETURNING_GUEST_SUCCESS";
export const RETURNING_GUEST_FAIL = "RETURNING_GUEST_FAIL";
export const RETURNING_GUEST_RESET = "RETURNING_GUEST_RESET";

export const PREBOOKED_GUEST_REQUEST = "PREBOOKED_GUEST_REQUEST";
export const PREBOOKED_GUEST_SUCCESS = "PREBOOKED_GUEST_SUCCESS";
export const PREBOOKED_GUEST_FAIL = "PREBOOKED_GUEST_FAIL";
export const PREBOOKED_GUEST_RESET = "PREBOOKED_GUEST_RESET";

export const ADDRETURNING_GUEST_REQUEST = "ADDRETURNING_GUEST_REQUEST";
export const ADDRETURNING_GUEST_SUCCESS = "ADDRETURNING_GUEST_SUCCESS";
export const ADDRETURNING_GUEST_FAIL = "ADDRETURNING_GUEST_FAIL";
export const ADDRETURNING_GUEST_RESET = "ADDRETURNING_GUEST_RESET";

export const CHECK_GUEST_REQUEST = "CHECK_GUEST_REQUEST";
export const CHECK_GUEST_SUCCESS = "CHECK_GUEST_SUCCESS";
export const CHECK_GUEST_FAIL = "CHECK_GUEST_FAIL";
export const CHECK_GUEST_RESET = "CHECK_GUEST_RESET";
